### ISSUE TITLE
自定义滑动条的长度

### ISSUE THREAD

**Issue by wsch88888** [cathu/SamrtScrollBar#1]
老哥啥时候支持自定义滑动条的长度啊

**Comment by cathu** [comment]
> 老哥啥时候支持自定义滑动条的长度啊

已经支持了啊

**Comment by wsch88888** [comment]
smart_slider_length 滑块长度，已经支持了么

**Comment by cathu** [comment]
> smart_slider_length 滑块长度，已经支持了么

你说滑块啊……看吧，要不你来试一试？

**Comment by wsch88888** [comment]
哈哈 好的，我也来试试看。不过kt还没用过，看看能不能搞定

**Comment by wsch88888** [comment]
老哥也太效率了 👍
