### ISSUE TITLE
【希望能够在代码中进行一些动态设置】

### ISSUE THREAD

**Issue by cathu** [cathu/SamrtScrollBar#2]
在自定义View中添加各种 setter 
@wsch88888

**Comment by wsch88888** [comment]
有没有啥具体需求啊，我来帮着一起加好了

**Comment by cathu** [comment]
> 有没有啥具体需求啊，我来帮着一起加好了

在Dev分支实现了拖拽，但是有些bug，现在想换个思路实现拖拽滑动……

**Comment by cathu** [comment]
费了点时间实现了…… 😂
