### ISSUE TITLE
小滑块，不太流畅，会出现跳动的情况

### ISSUE THREAD

**Issue by amelons** [cathu/SamrtScrollBar#5]
多个item列表中，小滑块，不太流畅，会出现跳动的情况，希望大佬能优化一下

**Comment by Xxj-star** [comment]
对 滑动慢的的时候 rv抖动

**Comment by cathu** [comment]
已经修复：https://github.com/cathu/SamrtScrollBar/commit/6054081f390228de82ef68b5c9ca37a1bd583a37
