### ISSUE TITLE
加载1w条数据后拖动卡顿

### ISSUE THREAD

**Issue by liverloop** [cathu/SamrtScrollBar#8]

**Comment by cathu** [comment]
原因：当有1w条数据后，RecyclerView#scrollBy 耗时超过100ms，这是主线程的工作无法避免（或许以后可以出一个SurfaceView的版本来彻底解决这个问题）。
修复：新增 SamrtScrollBar#setScrollingType(Int) 方法，当数据量比较大的时候传入 SamrtScrollBar.SCROLL_TYPE_ITEM
这样会使RecyclerView以项目为单位滚动，其原理是直接调用 requestLayout 方法更加省时。
commit: https://github.com/cathu/SamrtScrollBar/commit/0291867122973218c3610a38737a712c9fca3405
请更新到 0.1.2 版本。

**Comment by liverloop** [comment]
解决了
