### ISSUE TITLE
RecyclerView数据少的时候拖动滚动条直接崩溃

### ISSUE THREAD

**Issue by gyh792054863** [cathu/SamrtScrollBar#9]
scrollRecyclerViewByDistance方法的 ：bindView!!.scrollBy(0, ((orientationHandler.computeRecyclerViewTotalLength(bindView!!) - bindView!!.height) * (offsetRatio - lastOffsetRatio)).roundToInt())，报错：IllegalArgumentException: Cannot round NaN value.

**Comment by cathu** [comment]
感谢您发现的问题，已修复，请更新至0.1.3
